apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-deployment
  labels:
    app:  mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app:  mongodb
  template:
    metadata:
      labels:
        app:  mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo
        ports:
        - containerPort: 27017 
        env: # config file checked into a repo..ADMIN USERNAME & PASSWORD SHOULD NOT GO HERE. create a secret within K8 were these will live
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom: 
            secretKeyRef:
              name: mongo-secret
              key: mongo-root-username
        - name: MONGO_INITDB_ROOT_PASSWORD  
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: mongo-root-password
--- # these 3 dahes mean the beggining of a new file
apiVersion: v1
kind: Service
metadata:
  name: mongo-service
spec:
  selector:
    app:  mongodb
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017              