apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque  # default for key-value pairs
data:
    mongo-root-username: LW4gJ3VzZXJuYW1lJw0K
    mongo-root-password: LW4gJ3Bhc3N3b3JkJw0K 
         