apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque  # default for key-value pairs
data:
    mongo-root-username: ZZZZZZZZZZZZZZZZZ
    mongo-root-password: ZZZZZZZZZZZZZZZZZ
         
         
# TO CREATE A SECRET: Username and Password type the following in your terminal inside the folder u are creating your config files:
# echo -n 'username of choice' | base64
# echo -n 'password of choice' | base64    COPY the values to your secret yaml file
